name: Build and Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create version.txt
        run: 'echo "$(git rev-parse --short HEAD)" > version.txt'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: xsea-artifact
          path: target/xSea-1.0-SNAPSHOT.jar